sequenceDiagram
Title: オーナーが配布者に追加登録
participant Human AS オーナー
participant TOKEN
participant 残高 AS 候補者の残高
participant 配布者リスト
participant 全体　AS ブロックチェーン全体

Human->>TOKEN: addToDistributor()
TOKEN->>残高: 残高を確認(0であること)
TOKEN->>配布者リスト: 増員
TOKEN->>全体: emit AddedToDistributor()
TOKEN-->>Human: 処理結果
